name: "Install extra GAP packages"
description: "Clones and builds any GAP packages specified in the PACKAGES parameter"
inputs:
  PACKAGES:
    description: "List of extra GAP packages to clone and build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
      - name: "Clone packages"
        shell: bash
        run: |
          cd /opt/gap/pkg
          for pkg in ${{ inputs.PACKAGES }}; do
              rm -rf "${pkg##*/}"*
              if [[ "$pkg" =~ ^http ]] ; then
                  # looks like a full URL
                  git clone --depth 1 "$pkg"
              elif [[ "$pkg" =~ ^[^/]+/[^/]+$ ]] ; then
                  # looks like ORG/REPO
                  git clone --depth 1 https://github.com/"$pkg"
              elif [[ "$pkg" =~ ^[^/]+$ ]] ; then
                  # looks like just a REPO name
                  git clone --depth 1 https://github.com/gap-packages/"$pkg"
              else
                  echo "Invalid package"
                  exit 1
              fi
          done
      - name: "Build packages"
        shell:  bash
        run: |
          BuildPackagesOptions="--strict"
          cd /opt/gap/pkg
          for pkg in ${{ inputs.PACKAGES}}; do
              ../bin/BuildPackages.sh ${BuildPackagesOptions} $pkg*
          done
